#############################################################################
# Makefile for building: SatViewer
# Generated by qmake (3.0) (Qt 5.1.0) on: ?? 26. ??? 17:05:48 2013
# Project:  SatViewer.pro
# Template: subdirs
# Command: D:/usr/qt5/5.1.0/mingw48_32/bin/qmake.exe -o Makefile SatViewer.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:/usr/qt5/5.1.0/mingw48_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-satviewer \
		sub-models \
		sub-dialogs


sub-satviewer-qmake_all:  FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile
	cd satviewer/ && $(MAKE) -f Makefile qmake_all
sub-satviewer: FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile
sub-satviewer-make_first: FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-satviewer-all: FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-satviewer-clean: FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-satviewer-distclean: FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-satviewer-install_subtargets: FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-satviewer-uninstall_subtargets: FORCE
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-models-qmake_all:  FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile
	cd models/ && $(MAKE) -f Makefile qmake_all
sub-models: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile
sub-models-make_first: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-models-all: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-models-clean: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-models-distclean: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-models-install_subtargets: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-models-uninstall_subtargets: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-dialogs-qmake_all:  FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile
	cd dialogs/ && $(MAKE) -f Makefile qmake_all
sub-dialogs: FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile
sub-dialogs-make_first: FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-dialogs-all: FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-dialogs-clean: FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-dialogs-distclean: FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-dialogs-install_subtargets: FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-dialogs-uninstall_subtargets: FORCE
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: SatViewer.pro ../../../usr/qt5/5.1.0/mingw48_32/mkspecs/win32-g++/qmake.conf ../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/spec_pre.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/qdevice.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/device_config.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/common/shell-unix.conf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/qconfig.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_clucene.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_core.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_declarative.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_designer.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_gui.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_help.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_network.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qml.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_quick.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_script.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_sensors.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_serialport.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_sql.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_svg.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_v8.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_webkit.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_xml.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/qt_functions.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/qt_config.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/win32-g++/qmake.conf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/spec_post.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/exclusive_builds.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/default_pre.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/win32/default_pre.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/resolve_config.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/default_post.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/win32/rtti.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/warn_on.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/win32/windows.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/testcase_targets.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/exceptions.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/yacc.prf \
		../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/lex.prf \
		SatViewer.pro
	$(QMAKE) -o Makefile SatViewer.pro
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/spec_pre.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/qdevice.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/device_config.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/common/shell-unix.conf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/qconfig.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_axbase.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_axserver.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_bootstrap.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_clucene.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_concurrent.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_core.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_declarative.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_designer.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_designercomponents.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_gui.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_help.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_multimedia.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_network.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_opengl.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_platformsupport.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_printsupport.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qml.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qmltest.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_quick.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_quickparticles.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_script.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_scripttools.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_sensors.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_serialport.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_sql.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_svg.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_testlib.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_uitools.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_v8.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_webkit.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_widgets.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_xml.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/qt_functions.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/qt_config.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/win32-g++/qmake.conf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/spec_post.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/exclusive_builds.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/default_pre.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/win32/default_pre.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/resolve_config.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/default_post.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/win32/rtti.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/warn_on.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/win32/windows.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/testcase_targets.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/exceptions.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/yacc.prf:
../../../usr/qt5/5.1.0/mingw48_32/mkspecs/features/lex.prf:
SatViewer.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile SatViewer.pro

qmake_all: sub-satviewer-qmake_all sub-models-qmake_all sub-dialogs-qmake_all FORCE

make_first: sub-satviewer-make_first sub-models-make_first sub-dialogs-make_first FORCE
all: sub-satviewer-all sub-models-all sub-dialogs-all FORCE
clean: sub-satviewer-clean sub-models-clean sub-dialogs-clean FORCE
distclean: sub-satviewer-distclean sub-models-distclean sub-dialogs-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-satviewer-install_subtargets sub-models-install_subtargets sub-dialogs-install_subtargets FORCE
uninstall_subtargets: sub-satviewer-uninstall_subtargets sub-models-uninstall_subtargets sub-dialogs-uninstall_subtargets FORCE

sub-satviewer-sub_Debug:
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile debug
sub-models-sub_Debug:
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile debug
sub-dialogs-sub_Debug:
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-satviewer-sub_Debug sub-models-sub_Debug sub-dialogs-sub_Debug

sub-satviewer-sub_Release:
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile release
sub-models-sub_Release:
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile release
sub-dialogs-sub_Release:
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile release
release: sub-satviewer-sub_Release sub-models-sub_Release sub-dialogs-sub_Release

sub-satviewer-check:
	@test -d satviewer/ || mkdir -p satviewer/
	cd satviewer/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/satviewer/satviewer.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-models-check:
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/models/models.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-dialogs-check:
	@test -d dialogs/ || mkdir -p dialogs/
	cd dialogs/ && ( test -e Makefile || $(QMAKE) D:/work/pc/SatViewer/dialogs/dialogs.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-satviewer-check sub-models-check sub-dialogs-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

