#############################################################################
# Makefile for building: SatViewer
# Generated by qmake (2.01a) (Qt 4.8.2) on: ?? 8. ??? 20:53:31 2012
# Project:  SatViewer.pro
# Template: subdirs
# Command: e:/usr/qt/bin/qmake.exe -o Makefile SatViewer.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = e:/usr/qt/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-satviewer \
		sub-models \
		sub-dialogs

satviewer/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) satviewer/ || $(MKDIR) satviewer/ 
	cd satviewer/ && $(QMAKE) e:/work/pc/SatViewer/satviewer/satviewer.pro -o $(MAKEFILE)
sub-satviewer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) satviewer/ || $(MKDIR) satviewer/ 
	cd satviewer/ && $(QMAKE) e:/work/pc/SatViewer/satviewer/satviewer.pro -o $(MAKEFILE)
sub-satviewer: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE)
sub-satviewer-make_default: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) 
sub-satviewer-make_first: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) first
sub-satviewer-all: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) all
sub-satviewer-clean: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-satviewer-distclean: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-satviewer-install_subtargets: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) install
sub-satviewer-uninstall_subtargets: satviewer/$(MAKEFILE) FORCE
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) uninstall
models/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) models/ || $(MKDIR) models/ 
	cd models/ && $(QMAKE) e:/work/pc/SatViewer/models/models.pro -o $(MAKEFILE)
sub-models-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) models/ || $(MKDIR) models/ 
	cd models/ && $(QMAKE) e:/work/pc/SatViewer/models/models.pro -o $(MAKEFILE)
sub-models: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE)
sub-models-make_default: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE) 
sub-models-make_first: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE) first
sub-models-all: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE) all
sub-models-clean: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE) clean
sub-models-distclean: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE) distclean
sub-models-install_subtargets: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE) install
sub-models-uninstall_subtargets: models/$(MAKEFILE) FORCE
	cd models/ && $(MAKE) -f $(MAKEFILE) uninstall
dialogs/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) dialogs/ || $(MKDIR) dialogs/ 
	cd dialogs/ && $(QMAKE) e:/work/pc/SatViewer/dialogs/dialogs.pro -o $(MAKEFILE)
sub-dialogs-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) dialogs/ || $(MKDIR) dialogs/ 
	cd dialogs/ && $(QMAKE) e:/work/pc/SatViewer/dialogs/dialogs.pro -o $(MAKEFILE)
sub-dialogs: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE)
sub-dialogs-make_default: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) 
sub-dialogs-make_first: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) first
sub-dialogs-all: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) all
sub-dialogs-clean: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) clean
sub-dialogs-distclean: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-dialogs-install_subtargets: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) install
sub-dialogs-uninstall_subtargets: dialogs/$(MAKEFILE) FORCE
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: SatViewer.pro  ../../../usr/qt/mkspecs/default/qmake.conf ../../../usr/qt/mkspecs/qconfig.pri \
		../../../usr/qt/mkspecs/modules/qt_webkit_version.pri \
		../../../usr/qt/mkspecs/features/qt_functions.prf \
		../../../usr/qt/mkspecs/features/qt_config.prf \
		../../../usr/qt/mkspecs/win32-g++/qmake.conf \
		../../../usr/qt/mkspecs/features/exclusive_builds.prf \
		../../../usr/qt/mkspecs/features/default_pre.prf \
		../../../usr/qt/mkspecs/features/win32/default_pre.prf \
		../../../usr/qt/mkspecs/features/debug.prf \
		../../../usr/qt/mkspecs/features/debug_and_release.prf \
		../../../usr/qt/mkspecs/features/default_post.prf \
		../../../usr/qt/mkspecs/features/win32/default_post.prf \
		../../../usr/qt/mkspecs/features/win32/rtti.prf \
		../../../usr/qt/mkspecs/features/win32/exceptions.prf \
		../../../usr/qt/mkspecs/features/win32/stl.prf \
		../../../usr/qt/mkspecs/features/shared.prf \
		../../../usr/qt/mkspecs/features/warn_on.prf \
		../../../usr/qt/mkspecs/features/qt.prf \
		../../../usr/qt/mkspecs/features/win32/thread.prf \
		../../../usr/qt/mkspecs/features/moc.prf \
		../../../usr/qt/mkspecs/features/win32/windows.prf \
		../../../usr/qt/mkspecs/features/resources.prf \
		../../../usr/qt/mkspecs/features/uic.prf \
		../../../usr/qt/mkspecs/features/yacc.prf \
		../../../usr/qt/mkspecs/features/lex.prf \
		../../../usr/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile SatViewer.pro
../../../usr/qt/mkspecs/qconfig.pri:
../../../usr/qt/mkspecs/modules/qt_webkit_version.pri:
../../../usr/qt/mkspecs/features/qt_functions.prf:
../../../usr/qt/mkspecs/features/qt_config.prf:
../../../usr/qt/mkspecs/win32-g++/qmake.conf:
../../../usr/qt/mkspecs/features/exclusive_builds.prf:
../../../usr/qt/mkspecs/features/default_pre.prf:
../../../usr/qt/mkspecs/features/win32/default_pre.prf:
../../../usr/qt/mkspecs/features/debug.prf:
../../../usr/qt/mkspecs/features/debug_and_release.prf:
../../../usr/qt/mkspecs/features/default_post.prf:
../../../usr/qt/mkspecs/features/win32/default_post.prf:
../../../usr/qt/mkspecs/features/win32/rtti.prf:
../../../usr/qt/mkspecs/features/win32/exceptions.prf:
../../../usr/qt/mkspecs/features/win32/stl.prf:
../../../usr/qt/mkspecs/features/shared.prf:
../../../usr/qt/mkspecs/features/warn_on.prf:
../../../usr/qt/mkspecs/features/qt.prf:
../../../usr/qt/mkspecs/features/win32/thread.prf:
../../../usr/qt/mkspecs/features/moc.prf:
../../../usr/qt/mkspecs/features/win32/windows.prf:
../../../usr/qt/mkspecs/features/resources.prf:
../../../usr/qt/mkspecs/features/uic.prf:
../../../usr/qt/mkspecs/features/yacc.prf:
../../../usr/qt/mkspecs/features/lex.prf:
../../../usr/qt/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile SatViewer.pro

qmake_all: sub-satviewer-qmake_all sub-models-qmake_all sub-dialogs-qmake_all FORCE

make_default: sub-satviewer-make_default sub-models-make_default sub-dialogs-make_default FORCE
make_first: sub-satviewer-make_first sub-models-make_first sub-dialogs-make_first FORCE
all: sub-satviewer-all sub-models-all sub-dialogs-all FORCE
clean: sub-satviewer-clean sub-models-clean sub-dialogs-clean FORCE
distclean: sub-satviewer-distclean sub-models-distclean sub-dialogs-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-satviewer-install_subtargets sub-models-install_subtargets sub-dialogs-install_subtargets FORCE
uninstall_subtargets: sub-satviewer-uninstall_subtargets sub-models-uninstall_subtargets sub-dialogs-uninstall_subtargets FORCE

sub-satviewer-sub_Debug: satviewer/$(MAKEFILE)
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) debug
sub-models-sub_Debug: models/$(MAKEFILE)
	cd models/ && $(MAKE) -f $(MAKEFILE) debug
sub-dialogs-sub_Debug: dialogs/$(MAKEFILE)
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-satviewer-sub_Debug sub-models-sub_Debug sub-dialogs-sub_Debug

sub-satviewer-sub_Release: satviewer/$(MAKEFILE)
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) release
sub-models-sub_Release: models/$(MAKEFILE)
	cd models/ && $(MAKE) -f $(MAKEFILE) release
sub-dialogs-sub_Release: dialogs/$(MAKEFILE)
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) release
release: sub-satviewer-sub_Release sub-models-sub_Release sub-dialogs-sub_Release

sub-satviewer-check: satviewer/$(MAKEFILE)
	cd satviewer/ && $(MAKE) -f $(MAKEFILE) check
sub-models-check: models/$(MAKEFILE)
	cd models/ && $(MAKE) -f $(MAKEFILE) check
sub-dialogs-check: dialogs/$(MAKEFILE)
	cd dialogs/ && $(MAKE) -f $(MAKEFILE) check
check: sub-satviewer-check sub-models-check sub-dialogs-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

