name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install qt
        uses: jurplel/install-qt-action@v2
      - name: satviewer
        uses: actions/checkout@v2
      - name: create build 
        run: cmake -E make_directory ${{github.workspace}}/build        
      - name: configure cmake
        working-directory: ${{github.workspace}}/build
        run: cmake ..
      - name: build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
